#!/usr/bin/env python3
"""Compile the hwrt GLSL shaders to SPIR-V and embed them as C headers.

The generated headers are committed, so a normal build of the client needs no
Vulkan SDK and no shader compiler. Only rerun this after editing a .comp file.

Needs glslang; point HWRT_GLSLANG at the binary, or drop a release of
https://github.com/KhronosGroup/glslang into tools/_deps/glslang/.
"""

import os
import shutil
import struct
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHADERS = os.path.join(ROOT, "src", "engine", "hwrt", "shaders")

# (source file, C identifier)
TARGETS = [
    ("debug.comp", "hwrtdebugspv"),
    ("silhouette.comp", "hwrtsilhouettespv"),
    ("rtao.comp", "hwrtrtaospv"),
    ("hitshade.comp", "hwrthitshadespv"),
    ("hitlight.comp", "hwrthitlightspv"),
    ("skycompose.comp", "hwrtskycomposespv"),
]


def find_glslang():
    env = os.environ.get("HWRT_GLSLANG")
    if env and os.path.exists(env):
        return env
    for name in ("glslang", "glslangValidator"):
        for sub in ("glslang-bin", "glslang"):
            exe = os.path.join(ROOT, "tools", "_deps", sub, "bin", name + (".exe" if os.name == "nt" else ""))
            if os.path.exists(exe):
                return exe
        found = shutil.which(name)
        if found:
            return found
    sys.exit("glslang not found; set HWRT_GLSLANG or install it under tools/_deps/glslang")


def compile_one(glslang, source, identifier):
    src = os.path.join(SHADERS, source)
    with tempfile.TemporaryDirectory() as tmp:
        spv = os.path.join(tmp, "out.spv")
        subprocess.run([glslang, "-V", "--target-env", "vulkan1.2", "-o", spv, src], check=True)
        with open(spv, "rb") as f:
            blob = f.read()

    if len(blob) % 4:
        sys.exit("%s: SPIR-V blob is not a multiple of 4 bytes" % source)
    words = struct.unpack("<%dI" % (len(blob) // 4), blob)

    header = os.path.join(SHADERS, os.path.splitext(source)[0] + "_" + source.split(".")[-1] + ".h")
    lines = [
        "// Generated by tools/compile-hwrt-shaders.py from %s -- do not edit." % source,
        "",
        "static const uint32_t %s[] = {" % identifier,
    ]
    for i in range(0, len(words), 8):
        lines.append("    " + " ".join("0x%08x," % w for w in words[i:i + 8]))
    lines.append("};")
    lines.append("")
    with open(header, "w", newline="\n") as f:
        f.write("\n".join(lines))
    print("%s -> %s (%d words)" % (source, os.path.basename(header), len(words)))


def main():
    glslang = find_glslang()
    print("using %s" % glslang)
    for source, identifier in TARGETS:
        compile_one(glslang, source, identifier)


if __name__ == "__main__":
    main()
