#!/usr/bin/env python3
"""Generate the blue-noise tile hitlight.comp uses for its sky rays.

Writes src/engine/hwrt/shaders/bluenoise_tab.h (committed, like the SPIR-V
headers), so a normal build needs neither Python nor numpy. Only rerun this if
the tile itself has to change; the output is deterministic (fixed seeds), so a
rerun rewrites the same bytes.

What it is: two independent 128x128 void-and-cluster masks (Ulichney 1993,
"The void-and-cluster method for dither array generation"), toroidal, Gaussian
energy sigma 1.5. Each mask is a permutation of the ranks 0..16383, so every
threshold of it is an even scatter of pixels: neighbouring pixels always land
on both sides of an occluder's edge in the right proportion, which is what the
5x5 skyvis filter needs. Mask A feeds u1 (low 16 bits of each word), mask B u2
(high 16 bits); the value is (rank + 0.5) / 16384 quantised to 16 bits.
Generated here from scratch: no third-party noise data, no licence attached.

Needs numpy. Usage: python tools/generate-hwrt-bluenoise.py
"""

import os
import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "src", "engine", "hwrt", "shaders", "bluenoise_tab.h")

SIZE = 128
SIGMA = 1.5
SEEDS = (11, 23)


def kernel(size, sigma):
    d = np.arange(size)
    d = np.minimum(d, size - d)
    return np.exp(-(d[:, None] ** 2 + d[None, :] ** 2) / (2.0 * sigma * sigma))


def void_and_cluster(size, sigma, seed, density=0.1):
    rng = np.random.default_rng(seed)
    k = kernel(size, sigma)
    n = size * size
    pattern = np.zeros((size, size), bool)
    pattern.flat[rng.choice(n, size=int(n * density), replace=False)] = True

    energy = np.zeros((size, size))

    def splat(y, x, sign):
        energy[:] += sign * np.roll(np.roll(k, y, 0), x, 1)

    def rebuild(p):
        energy[:] = 0
        for y, x in zip(*np.nonzero(p)):
            splat(y, x, 1)

    def tightest(p):
        return np.unravel_index(np.argmax(np.where(p, energy, -np.inf)), energy.shape)

    def largest_void(p):
        return np.unravel_index(np.argmin(np.where(~p, energy, np.inf)), energy.shape)

    # Initial binary pattern: move the tightest cluster into the largest void
    # until that no longer changes anything.
    rebuild(pattern)
    for _ in range(n):
        a = tightest(pattern)
        pattern[a] = False
        splat(*a, -1)
        b = largest_void(pattern)
        pattern[b] = True
        splat(*b, 1)
        if b == a:
            break

    rank = np.zeros((size, size), np.int64)
    ones = int(pattern.sum())
    # Phase 1: ranks ones-1 .. 0 by removing the tightest clusters.
    p = pattern.copy()
    rebuild(p)
    for r in range(ones - 1, -1, -1):
        a = tightest(p)
        p[a] = False
        splat(*a, -1)
        rank[a] = r
    # Phases 2 and 3: ranks ones .. n-1 by filling the largest voids.
    p = pattern.copy()
    rebuild(p)
    for r in range(ones, n):
        b = largest_void(p)
        p[b] = True
        splat(*b, 1)
        rank[b] = r
    return rank


def main():
    n = SIZE * SIZE
    a = void_and_cluster(SIZE, SIGMA, SEEDS[0])
    b = void_and_cluster(SIZE, SIGMA, SEEDS[1])
    qa = np.minimum(np.floor((a + 0.5) / n * 65536.0), 65535).astype(np.uint32)
    qb = np.minimum(np.floor((b + 0.5) / n * 65536.0), 65535).astype(np.uint32)
    words = (qa | (qb << 16)).ravel()
    lines = [
        "// Generated by tools/generate-hwrt-bluenoise.py -- do not edit.",
        "// %dx%d void-and-cluster masks (sigma %.1f, seeds %d/%d): u1 low 16 bits, u2 high 16 bits." % (SIZE, SIZE, SIGMA, SEEDS[0], SEEDS[1]),
        "",
        "static const int hwrtskybluenoisetabsize = %d;" % SIZE,
        "static const uint32_t hwrtskybluenoisetab[%d] = {" % n,
    ]
    for i in range(0, n, 8):
        lines.append("    " + " ".join("0x%08x," % w for w in words[i:i + 8]))
    lines.append("};")
    lines.append("")
    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(lines))
    print("wrote %s (%d words)" % (OUT, n))


if __name__ == "__main__":
    main()
